"""add soil_type to fields

Revision ID: 232a4640c9d5
Revises: 7c867e9180a9
Create Date: 2026-08-25 10:28:19.867923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '232a4640c9d5'
down_revision: Union[str, Sequence[str], None] = '7c867e9180a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('soil_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'soil_type')
    # ### end Alembic commands ###
