"""add recommendation jobs and field engine state

Revision ID: 7c867e9180a9
Revises: fc6665c4aa9c
Create Date: 2026-08-19 12:40:33.848634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c867e9180a9'
down_revision: Union[str, Sequence[str], None] = 'fc6665c4aa9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('field_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fields', sa.Column('engine_psi_state', sa.JSON(), nullable=True))
    op.add_column('fields', sa.Column('engine_theta_infiltre', sa.Float(), nullable=False, server_default='0'))
    op.add_column('fields', sa.Column('engine_last_julian_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'engine_last_julian_day')
    op.drop_column('fields', 'engine_theta_infiltre')
    op.drop_column('fields', 'engine_psi_state')
    op.drop_table('recommendation_jobs')
    # ### end Alembic commands ###
